<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="8" total="14" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-17T18:02:41 IST" name="Suite" finished-at="2023-07-17T18:04:14 IST" duration-ms="93457">
    <groups>
      <group name="RegressionTest">
        <method signature="CreateCampaign.createCampaign()[pri:0, instance:campaign.CreateCampaign@4722ef0c]" name="createCampaign" class="campaign.CreateCampaign"/>
        <method signature="CreateProduct.createProduct()[pri:0, instance:product.CreateProduct@48e1f6c7]" name="createProduct" class="product.CreateProduct"/>
      </group> <!-- RegressionTest -->
      <group name="smokeTest">
        <method signature="CreateCampaign.createCampaign()[pri:0, instance:campaign.CreateCampaign@4722ef0c]" name="createCampaign" class="campaign.CreateCampaign"/>
        <method signature="CreateProduct.createProduct()[pri:0, instance:product.CreateProduct@48e1f6c7]" name="createProduct" class="product.CreateProduct"/>
      </group> <!-- smokeTest -->
    </groups>
    <test started-at="2023-07-17T18:02:41 IST" name="Test" finished-at="2023-07-17T18:04:14 IST" duration-ms="93457">
      <class name="campaign.CreateCampaign">
        <test-method is-config="true" signature="BC()[pri:0, instance:campaign.CreateCampaign@4722ef0c]" started-at="2023-07-17T18:03:34 IST" name="BC" finished-at="2023-07-17T18:03:35 IST" duration-ms="914" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BC -->
        <test-method is-config="true" signature="BM()[pri:0, instance:campaign.CreateCampaign@4722ef0c]" started-at="2023-07-17T18:03:35 IST" name="BM" finished-at="2023-07-17T18:03:39 IST" duration-ms="3601" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BM -->
        <test-method signature="createCampaign()[pri:0, instance:campaign.CreateCampaign@4722ef0c]" started-at="2023-07-17T18:03:39 IST" name="createCampaign" finished-at="2023-07-17T18:03:56 IST" duration-ms="16756" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Qspider5] but found [ChromeDriver: chrome on WINDOWS (2879eeb9ff64e578e89b9571bb28ccda)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Qspider5] but found [ChromeDriver: chrome on WINDOWS (2879eeb9ff64e578e89b9571bb28ccda)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at campaign.CreateCampaign.createCampaign(CreateCampaign.java:118)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCampaign -->
        <test-method is-config="true" signature="AM()[pri:0, instance:campaign.CreateCampaign@4722ef0c]" started-at="2023-07-17T18:03:56 IST" name="AM" finished-at="2023-07-17T18:03:57 IST" duration-ms="1817" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM -->
      </class> <!-- campaign.CreateCampaign -->
      <class name="product.CreateProduct">
        <test-method is-config="true" signature="BC()[pri:0, instance:product.CreateProduct@48e1f6c7]" started-at="2023-07-17T18:03:57 IST" name="BC" finished-at="2023-07-17T18:03:59 IST" duration-ms="1192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BC -->
        <test-method is-config="true" signature="BM()[pri:0, instance:product.CreateProduct@48e1f6c7]" started-at="2023-07-17T18:03:59 IST" name="BM" finished-at="2023-07-17T18:04:02 IST" duration-ms="3609" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BM -->
        <test-method signature="createProduct()[pri:0, instance:product.CreateProduct@48e1f6c7]" started-at="2023-07-17T18:04:02 IST" name="createProduct" finished-at="2023-07-17T18:04:13 IST" duration-ms="10784" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createProduct -->
        <test-method is-config="true" signature="AM()[pri:0, instance:product.CreateProduct@48e1f6c7]" started-at="2023-07-17T18:04:13 IST" name="AM" finished-at="2023-07-17T18:04:14 IST" duration-ms="1211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM -->
      </class> <!-- product.CreateProduct -->
      <class name="organization.CreateOrganization">
        <test-method is-config="true" signature="BS()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:02:41 IST" name="BS" finished-at="2023-07-17T18:02:41 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BS -->
        <test-method is-config="true" signature="BT()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:02:41 IST" name="BT" finished-at="2023-07-17T18:02:41 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BT -->
        <test-method is-config="true" signature="BC()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:02:41 IST" name="BC" finished-at="2023-07-17T18:02:44 IST" duration-ms="3439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BC -->
        <test-method is-config="true" signature="BM()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:02:44 IST" name="BM" finished-at="2023-07-17T18:02:55 IST" duration-ms="10394" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BM -->
        <test-method retried="true" signature="createOrganization()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:02:55 IST" name="createOrganization" finished-at="2023-07-17T18:03:04 IST" duration-ms="9432" status="SKIP">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because "sh" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because "sh" is null
at Generic_Utility.Excel_Utility.getExcelData(Excel_Utility.java:23)
at organization.CreateOrganization.createOrganization(CreateOrganization.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrganization -->
        <test-method is-config="true" signature="AM()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:03:04 IST" name="AM" finished-at="2023-07-17T18:03:06 IST" duration-ms="2065" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM -->
        <test-method is-config="true" signature="BM()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:03:06 IST" name="BM" finished-at="2023-07-17T18:03:09 IST" duration-ms="3073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BM -->
        <test-method retried="true" signature="createOrganization()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:03:09 IST" name="createOrganization" finished-at="2023-07-17T18:03:13 IST" duration-ms="3465" status="SKIP">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because "sh" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because "sh" is null
at Generic_Utility.Excel_Utility.getExcelData(Excel_Utility.java:23)
at organization.CreateOrganization.createOrganization(CreateOrganization.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrganization -->
        <test-method is-config="true" signature="AM()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:03:13 IST" name="AM" finished-at="2023-07-17T18:03:16 IST" duration-ms="3169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM -->
        <test-method is-config="true" signature="BM()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:03:16 IST" name="BM" finished-at="2023-07-17T18:03:19 IST" duration-ms="2970" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BM -->
        <test-method retried="true" signature="createOrganization()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:03:19 IST" name="createOrganization" finished-at="2023-07-17T18:03:23 IST" duration-ms="4381" status="SKIP">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because "sh" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because "sh" is null
at Generic_Utility.Excel_Utility.getExcelData(Excel_Utility.java:23)
at organization.CreateOrganization.createOrganization(CreateOrganization.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrganization -->
        <test-method is-config="true" signature="AM()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:03:23 IST" name="AM" finished-at="2023-07-17T18:03:25 IST" duration-ms="1912" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM -->
        <test-method is-config="true" signature="BM()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:03:25 IST" name="BM" finished-at="2023-07-17T18:03:28 IST" duration-ms="3142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BM -->
        <test-method signature="createOrganization()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:03:28 IST" name="createOrganization" finished-at="2023-07-17T18:03:33 IST" duration-ms="4664" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because "sh" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because "sh" is null
at Generic_Utility.Excel_Utility.getExcelData(Excel_Utility.java:23)
at organization.CreateOrganization.createOrganization(CreateOrganization.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrganization -->
        <test-method is-config="true" signature="AM()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:03:33 IST" name="AM" finished-at="2023-07-17T18:03:34 IST" duration-ms="1418" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM -->
        <test-method is-config="true" signature="AT()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:04:14 IST" name="AT" finished-at="2023-07-17T18:04:14 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AT -->
        <test-method is-config="true" signature="AS()[pri:0, instance:organization.CreateOrganization@5f8e8a9d]" started-at="2023-07-17T18:04:14 IST" name="AS" finished-at="2023-07-17T18:04:14 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AS -->
      </class> <!-- organization.CreateOrganization -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
